version: 2
general:
  artifacts:

do_steps: &do_steps
 steps:
  - run: echo "$CROSS_COMPILE" > ~/_cross_compile
  - restore_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        if ! [ -d .git ]; then
          git clone --depth=1 $CIRCLE_REPOSITORY_URL .;
        fi
        if [[ $CIRCLE_BRANCH == pull/* ]]; then
           git fetch --depth=1 origin $CIRCLE_BRANCH/head;
        else
           git fetch --depth=1 origin $CIRCLE_BRANCH;
        fi
        git reset --hard $CIRCLE_SHA1
  - save_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
      paths:
        - /home/ubuntu/project/.git
  - run:
      name: clean
      command: |
        make mrproper
        cd tools/lkl && make clean-conf
        rm -rf ~/junit
  - run: mkdir -p /home/ubuntu/.ccache
  - restore_cache:
      key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}
  - run:
      name: start emulator
      command: |
        if [[ $CROSS_COMPILE == *android* ]]; then
          emulator -avd Nexus5_API24 -no-window -no-audio -no-boot-anim;
        elif [[ $CROSS_COMPILE == *freebsd* ]] || [[ -n "$LKL_QEMU_TEST" ]]; then
          cd /home/ubuntu && eval $QEMU
        fi
      background: true
  - run: cd tools/lkl && make -j8 ${MKARG}
  - run: mkdir -p ~/destdir && cd tools/lkl && make DESTDIR=~/destdir
  - save_cache:
     paths:
       - /home/ubuntu/.ccache
     key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
  - store_artifacts:
      path: ~/destdir
## Customize the test machine
jobs:
  android-arm32:
   docker:
     - image: lkldocker/circleci-android-arm32:0.6
   environment:
     CROSS_COMPILE: "arm-linux-androideabi-"
     LKL_ANDROID_TEST: 1
     ANDROID_SDK_ROOT: /home/ubuntu/android-sdk
   <<: *do_steps

  android-aarch64:
   docker:
     - image: lkldocker/circleci-android-arm64:0.6
   environment:
     CROSS_COMPILE: "aarch64-linux-android-"
     LKL_ANDROID_TEST: 1
     ANDROID_SDK_ROOT: /home/ubuntu/android-sdk
   <<: *do_steps
workflows:
  version: 2
  build:
    jobs:
     - android-arm32
     - android-aarch64
